import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import {
  hexFromArgb,
  sourceColorFromImage,
  Hct,
  SchemeTonalSpot,
  MaterialDynamicColors,
} from '@material/material-color-utilities'
import { useEffect, useState } from 'react'

const tokens = [
  'primaryPaletteKeyColor',
  'secondaryPaletteKeyColor',
  'tertiaryPaletteKeyColor',
  'neutralPaletteKeyColor',
  'neutralVariantPaletteKeyColor',
  'background',
  'onBackground',
  'surface',
  'surfaceDim',
  'surfaceBright',
  'surfaceContainerLowest',
  'surfaceContainerLow',
  'surfaceContainer',
  'surfaceContainerHigh',
  'surfaceContainerHighest',
  'onSurface',
  'surfaceVariant',
  'onSurfaceVariant',
  'inverseSurface',
  'inverseOnSurface',
  'outline',
  'outlineVariant',
  'shadow',
  'scrim',
  'surfaceTint',
  'primary',
  'onPrimary',
  'primaryContainer',
  'onPrimaryContainer',
  'inversePrimary',
  'secondary',
  'onSecondary',
  'secondaryContainer',
  'onSecondaryContainer',
  'tertiary',
  'onTertiary',
  'tertiaryContainer',
  'onTertiaryContainer',
  'error',
  'onError',
  'errorContainer',
  'onErrorContainer',
  'primaryFixed',
  'primaryFixedDim',
  'onPrimaryFixed',
  'onPrimaryFixedVariant',
  'secondaryFixed',
  'secondaryFixedDim',
  'onSecondaryFixed',
  'onSecondaryFixedVariant',
  'tertiaryFixed',
  'tertiaryFixedDim',
  'onTertiaryFixed',
  'onTertiaryFixedVariant',
]

export default function Home() {
  const [selectedImage, setSelectedImage] = useState<string | null>(null)
  const [theme, setTheme] = useState<any>({})

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      setSelectedImage(URL.createObjectURL(e.target.files[0]))
    }
  }

  useEffect(() => {
    const imageEle = document.getElementById('image') as HTMLImageElement

    if (imageEle) {
      sourceColorFromImage(imageEle).then((source) => {
        const hct = Hct.fromInt(source)
        const scheme = new SchemeTonalSpot(hct, false, 0)
        const darkScheme = new SchemeTonalSpot(hct, true, 0)

        // @ts-ignore
        const getDynamicColors = (scheme) =>
          Object.fromEntries(
            tokens.map((token) => {
              // @ts-ignore
              const num = MaterialDynamicColors[token].getArgb(scheme)

              return [token, hexFromArgb(num)]
            })
          )

        const theme = {
          source,
          schemes: {
            light: getDynamicColors(scheme),
            dark: getDynamicColors(darkScheme),
          },
          palettes: {
            primary: scheme.primaryPalette,
            secondary: scheme.secondaryPalette,
            tertiary: scheme.tertiaryPalette,
            neutral: scheme.neutralPalette,
            neutralVariant: scheme.neutralVariantPalette,
            error: scheme.errorPalette,
          },
          // customColors: customColors.map((c) =>
          //   customColor(source, c, variant, contrastLevel)
          // ),
        }

        setTheme(theme)
      })

      // themeFromImage(imageEle, [
      //   {
      //     name: 'warn',
      //     value: argbFromHex('#ff0000'),
      //     blend: true,
      //   },
      // ]).then((theme) => {
      //   console.log(theme)
      //   setTheme(theme)

      //   console.log(applyTheme(theme, { target: document.body, dark: true }))
      // })
    }
  }, [selectedImage])

  return (
    <>
      <Head>
        <title>Theme Color Tool</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <input type='file' accept='image/*' onChange={handleImageChange} />

        <br />

        {selectedImage && (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            id='image'
            src={selectedImage}
            alt='Selected'
            style={{ width: 300 }}
          />
        )}

        <pre>{JSON.stringify(theme, null, 4)}</pre>
      </main>
    </>
  )
}
