import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import {
  argbFromHex,
  themeFromSourceColor,
  applyTheme,
  themeFromImage,
} from '@material/material-color-utilities'
import { useEffect, useState } from 'react'

const primary = '#6750A4'
const secondary = '#958DA5'
const tertiary = '#B58392'
const error = '#E46962'
const neutral = '#938F96'
const NeutralVariant = '#938F99'

const external = '#F5C700'

// Get the theme from a hex color
const theme = themeFromSourceColor(argbFromHex('#f82506'), [
  {
    name: 'warn',
    value: argbFromHex('#F5C700'),
    blend: true,
  },
])

export default function Home() {
  const [selectedImage, setSelectedImage] = useState<string | null>(null)

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      setSelectedImage(URL.createObjectURL(e.target.files[0]))
    }
  }

  useEffect(() => {
    const imageEle = document.getElementById('image') as HTMLImageElement

    if (imageEle) {
      themeFromImage(imageEle, [
        {
          name: 'custom-1',
          value: argbFromHex('#ff0000'),
          blend: true,
        },
      ]).then((theme) => {
        console.log(theme)
      })
    }
  }, [selectedImage])

  return (
    <>
      <Head>
        <title>Theme Color Tool</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <input type='file' accept='image/*' onChange={handleImageChange} />

        {selectedImage && (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            id='image'
            src={selectedImage}
            alt='Selected'
            style={{ width: '200px' }}
          />
        )}

        <pre>{JSON.stringify(theme, null, 4)}</pre>
      </main>
    </>
  )
}
